version: '3.9'
services:
  traefik:
    image: traefik:2.6
    command:
      --providers.docker=true
      --providers.docker.exposedByDefault=false
      --entryPoints.http.address=:80
    ports:
      - "80:80"
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public

  client:
    build:
      context: client/docker/dev/nginx
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.client.rule=Host(`client.pharm.test`)
      - traefik.http.routers.client.entryPoints=http
      - traefik.http.services.frontend.loadBalancer.server.port=80

  client-node:
    build:
      context: client/docker/dev/node
    environment:
      API_URL: http://pharm.test
    volumes:
      - ./client:/app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn dev"

  client-node-cli:
    build:
      context: client/docker/dev/node
    volumes:
      - ./client:/app
  
  panel:
    build:
      context: panel/docker/dev/nginx
    environment:
      API_URL: http://pharm.test
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.panel.rule=Host(`panel.pharm.test`)
      - traefik.http.routers.panel.entryPoints=http
      - traefik.http.services.panel.loadBalancer.server.port=80

  panel-node:
    build:
      context: panel/docker/dev/node
    environment:
      API_URL: http://pharm.test
    volumes:
      - ./panel:/app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"

  panel-node-cli:
    build:
      context: panel/docker/dev/node
    volumes:
      - ./panel:/app

  site:
    build:
      context: site/docker
      dockerfile: dev/nginx/Dockerfile
    volumes:
      - ./site:/app
      - uploads:/app/storage/app/public
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.site.rule=Host(`pharm.test`) || Host(`www.pharm.test`)
      - traefik.http.routers.site.entryPoints=http
      - traefik.http.services.site.loadBalancer.server.port=80
      - traefik.http.middlewares.site-redirect.redirectRegex.regex=^(https?://)www.pharm.test/(.*)$$
      - traefik.http.middlewares.site-redirect.redirectRegex.replacement=$${1}pharm.test/$${2}
      - traefik.http.middlewares.site-redirect.redirectRegex.permanent=true
      - traefik.http.routers.site.middlewares=site-redirect

  site-php-fpm:
    build:
      context: site/docker
      dockerfile: dev/php-fpm/Dockerfile
    environment:
      APP_NAME: Сеть аптек 120/80
      APP_URL: http://pharm.test
      APP_ENV: local
      APP_DEBUG: true
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      DB_CONNECTION: pgsql
      DB_HOST: db-postgres
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: secret
      BROADCAST_DRIVER: redis
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120
      SESSION_DOMAIN: '.pharm.test'
      SANCTUM_STATEFUL_DOMAINS: '*.pharm.test'
      CORS_ORIGIN: 'http://panel.pharm.test|http://client.pharm.test'
      REDIS_HOST: redis
      REDIS_CLIENT: predis
      MAIL_HOST: mailer
      MAIL_FROM_ADDRESS: info@pharm.test
      MAIL_FROM_NAME: Сеть аптек 120/80
      FILESYSTEM_DRIVER: public
    volumes:
      - ./site:/app
      - uploads:/app/storage/app/public

  site-php-cli:
    build:
      context: site/docker
      dockerfile: dev/php-cli/Dockerfile
    environment:
      APP_NAME: Сеть аптек 120/80
      APP_URL: http://pharm.test
      APP_ENV: local
      APP_DEBUG: true
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      DB_CONNECTION: pgsql
      DB_HOST: db-postgres
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: secret
      BROADCAST_DRIVER: redis
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120
      SESSION_DOMAIN: '.pharm.test'
      SANCTUM_STATEFUL_DOMAINS: '*.pharm.test'
      REDIS_HOST: redis
      REDIS_CLIENT: predis
      MAIL_HOST: mailer
      MAIL_FROM_ADDRESS: info@pharm.test
      MAIL_FROM_NAME: Сеть аптек 120/80
      FILESYSTEM_DRIVER: public
    volumes:
      - ./site:/app
      - uploads:/app/storage/app/public

  site-node:
    build:
      context: site/docker/dev/node
    volumes:
      - ./site:/app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn watch"

  site-node-cli:
    build:
      context: site/docker/dev/node
    volumes:
      - ./site:/app

  db-postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  mailer:
    image: mailhog/mailhog
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.mailer.rule=Host(`mailer.pharm.test`)
      - traefik.http.routers.mailer.entryPoints=http
      - traefik.http.services.mailer.loadBalancer.server.port=8085

  redis:
    image: redis:6.2-alpine
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.redis.rule=Host(`redis.pharm.test`)
      - traefik.http.routers.redis.entryPoints=http
      - traefik.http.services.redis.loadBalancer.server.port=6379

volumes:
  db-postgres:
  uploads:

networks:
  traefik-public:
    name: traefik-public
