version: "3.9"
services:
  cron:
    image: crazymax/swarm-cronjob:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LOG_LEVEL: info
    deploy:
      placement:
        constraints: [ node.role == manager ]

    gateway:
      image: ${REGISTRY}/auction-gateway:${IMAGE_TAG}
      volumes:
        - /etc/letsencrypt:/etc/letsencrypt:ro
        - /var/www/html:/var/www/html:ro
      ports:
        - "80:80"
        - "443:443"
      deploy:
        mode: replicated
        replicas: 2
        update_config:
          parallelism: 1
          delay: 10s
        placement:
          constraints: [ node.role == manager ]

  panel:
    image: ${REGISTRY}/pharm-panel:${IMAGE_TAG}
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s

  site:
    image: ${REGISTRY}/pharm-site:${IMAGE_TAG}
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s

  site-php-fpm:
    image: ${REGISTRY}/pharm-site-php-fpm:${IMAGE_TAG}
    environment:
      APP_NAME: Сеть аптек 120/80
      APP_URL: https://аптека05.рф
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      DB_CONNECTION: pgsql
      DB_HOST: db-postgres
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: ${DB_PASSWORD}
      BROADCAST_DRIVER: redis
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120
      SESSION_DOMAIN: '.аптека05.рф'
      SANCTUM_STATEFUL_DOMAINS: '*.аптека05.рф'
      REDIS_HOST: redis
      REDIS_CLIENT: predis
      MAIL_HOST: smtp.yandex.ru
      MAIL_PORT: 465
      MAIL_USERNAME: info@120на80.рф
      MAIL_PASSWORD: info12345
      MAIL_FROM_ADDRESS: info@120на80.рф
      MAIL_FROM_NAME: ${APP_NAME}
    volumes:
      - uploads:/app/storage/app/public
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s

  site-migration:
    image: ${REGISTRY}/pharm-site-php-cli:${IMAGE_TAG}
    environment:
      APP_NAME: Сеть аптек 120/80
      APP_URL: https://аптека05.рф
      LOG_CHANNEL: stack
      LOG_LEVEL: debug
      DB_CONNECTION: pgsql
      DB_HOST: db-postgres
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: ${DB_PASSWORD}
      BROADCAST_DRIVER: redis
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120
      SESSION_DOMAIN: '.аптека05.рф'
      SANCTUM_STATEFUL_DOMAINS: '*.аптека05.рф'
      REDIS_HOST: redis
      REDIS_CLIENT: predis
      MAIL_HOST: smtp.yandex.ru
      MAIL_PORT: 465
      MAIL_USERNAME: info@120на80.рф
      MAIL_PASSWORD: info12345
      MAIL_FROM_ADDRESS: info@120на80.рф
      MAIL_FROM_NAME: ${APP_NAME}
    command: sh -c 'wait-for-it db-postgres:5432 -t 60 && php artisan migrate --force'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

  db-postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: app
    volumes:
      - db-postgres:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [ node.role == manager ]
      endpoint_mode: dnsrr

  db-backup:
    image: ${REGISTRY}/pharm-db-backup:${IMAGE_TAG}
    environment:
      BACKUP_NAME: pharm-postgres
      POSTGRES_HOST: db-postgres
      POSTGRES_USERNAME: app
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: app
      AWS_ACCESS_KEY_ID: storage_app
      AWS_SECRET_ACCESS_KEY: storage_secret
      AWS_DEFAULT_REGION: region
      S3_ENDPOINT: http://backup-storage:9000
      S3_BUCKET: backup
    command: sh -c 'wait-for-it db-postgres:5432 -t 60 && backup'
    deploy:
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=0 * * * *
        - swarm.cronjob.skip-running=true
      replicas: 0
      restart_policy:
        condition: none
  
  redis:
    image: redis:6.2-alpine
    deploy:
      placement:
        constraints: [ node.role == manager ]

volumes:
  db-postgres:
  uploads:
